apiVersion: v1
kind: Service
metadata:
  name: weblate
spec:
  selector:
    app: weblate
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: api
      protocol: TCP
      port: 5000
      targetPort: 5000
