apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: secretstore-5stack
  namespace: 5stack
spec:
  provider:
    vault:
      server: $(EXTERNAL_SECRETS_URL)
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: "5stack"