apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-secrets
  namespace: 5stack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-5stack
    kind: SecretStore
  target:
    name: api-secrets
  data:
    - secretKey: APP_KEY
      remoteRef:
        key: api
        property: APP_KEY
    - secretKey: ENC_SECRET
      remoteRef:
        key: api
        property: ENC_SECRET
    - secretKey: K3S_TOKEN
      remoteRef:
        key: api
        property: K3S_TOKEN
