apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-secrets
  namespace: 5stack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-5stack
    kind: SecretStore
  target:
    name: discord-secrets
  data:
    - secretKey: DISCORD_CLIENT_ID
      remoteRef:
        key: discord
        property: DISCORD_CLIENT_ID
    - secretKey: DISCORD_CLIENT_SECRET
      remoteRef:
        key: discord
        property: DISCORD_CLIENT_SECRET
    - secretKey: DISCORD_BOT_TOKEN
      remoteRef:
        key: discord
        property: DISCORD_BOT_TOKEN 