apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: faceit-secrets
  namespace: 5stack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-5stack
    kind: SecretStore
  target:
    name: faceit-secrets
  data:
    - secretKey: FACEIT_API_KEY
      remoteRef:
        key: faceit
        property: FACEIT_API_KEY 