apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-secrets
  namespace: 5stack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-5stack
    kind: SecretStore
  target:
    name: s3-secrets
  data:
    - secretKey: S3_ACCESS_KEY
      remoteRef:
        key: s3
        property: S3_ACCESS_KEY
    - secretKey: S3_SECRET
      remoteRef:
        key: s3
        property: S3_SECRET