apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: steam-secrets
  namespace: 5stack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-5stack
    kind: SecretStore
  target:
    name: steam-secrets
  data:
    - secretKey: STEAM_WEB_API_KEY
      remoteRef:
        key: steam
        property: STEAM_WEB_API_KEY 