apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: timescaledb-secrets
  namespace: 5stack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-5stack
    kind: SecretStore
  target:
    name: timescaledb-secrets
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: timescaledb
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_CONNECTION_STRING
      remoteRef:
        key: timescaledb
        property: POSTGRES_CONNECTION_STRING 