apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: typesense-secrets
  namespace: 5stack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-5stack
    kind: SecretStore
  target:
    name: typesense-secrets
  data:
    - secretKey: TYPESENSE_API_KEY
      remoteRef:
        key: typesense
        property: TYPESENSE_API_KEY 