apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: 5stack

resources:
  - deployment.yaml

secretGenerator:
  - name: dev-server-secrets
    envs:
      - dev-server-secrets.env