apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  
secretGenerator:
  - name: api-secrets
    type: Opaque
    namespace: 5stack
    envs:
      - api-secrets.env

  - name: timescaledb-secrets
    type: Opaque
    namespace: 5stack
    envs:
      - timescaledb-secrets.env
  - name: tailscale-secrets
    type: Opaque
    namespace: 5stack
    envs:
      - tailscale-secrets.env
  - name: steam-secrets
    type: Opaque
    namespace: 5stack
    envs:
      - steam-secrets.env
  - name: hasura-secrets
    type: Opaque
    namespace: 5stack
    envs:
      - hasura-secrets.env
  - name: discord-secrets
    type: Opaque
    namespace: 5stack
    envs:
      - discord-secrets.env
  - name: s3-secrets
    type: Opaque
    namespace: 5stack
    envs:
      - s3-secrets.env
  - name: redis-secrets
    type: Opaque
    namespace: 5stack
    envs:
      - redis-secrets.env
  - name: typesense-secrets
    type: Opaque
    namespace: 5stack
    envs:
      - typesense-secrets.env
  - name: minio-secrets
    type: Opaque
    namespace: 5stack
    envs:
      - minio-secrets.env
  - name: faceit-secrets
    type: Opaque
    namespace: 5stack
    envs:
      - faceit-secrets.env 