apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - api
  - game-server-node-connector
  - hasura
  - minio
  - timescaledb
  - redis
  - typesense
  - web
  - volumes
  - nginx 


configMapGenerator:
  - name: api-config
    namespace: 5stack
    envs:
      - properties/api-config.env
  - name: typesense-config
    namespace: 5stack
    envs:
      - properties/typesense-config.env
    behavior: merge
  - name: s3-config
    namespace: 5stack
    envs:
      - properties/s3-config.env
  - name: nginx-config
    namespace: 5stack
    envs:
      - properties/nginx-config.env

replacements:
- source:
    kind: ConfigMap
    name: api-config
    fieldPath: data.WS_DOMAIN
  targets:
  - select:
      kind: Ingress
      name: ws
    fieldPaths:
    - spec.rules.0.host
- source:
    kind: ConfigMap
    name: api-config
    fieldPath: data.API_DOMAIN
  targets:
  - select:
      kind: Ingress
      name: api
    fieldPaths:
    - spec.rules.0.host
- source:
    kind: ConfigMap
    name: api-config
    fieldPath: data.DEMOS_DOMAIN
  targets:
  - select:
      kind: Ingress
      name: demos
    fieldPaths:
    - spec.rules.0.host
- source:
    kind: ConfigMap
    name: api-config
    fieldPath: data.WEB_DOMAIN
  targets:
  - select:
      kind: Ingress
      name: api
    fieldPaths:
    - spec.rules.1.host
  - select:
      kind: Ingress
      name: web
    fieldPaths:
    - spec.rules.0.host
- source:
    kind: ConfigMap
    name: s3-config
    fieldPath: data.S3_CONSOLE_HOST
  targets:
  - select:
      kind: Ingress
      name: s3-console
    fieldPaths:
    - spec.rules.0.host
- source:
    kind: ConfigMap
    name: typesense-config
    fieldPath: data.TYPESENSE_HOST
  targets:
  - select:
      kind: Ingress
      name: typesense
    fieldPaths:
    - spec.rules.0.host
- source:
    kind: ConfigMap
    name: nginx-config
    fieldPath: data.HTTP_PORT
  targets:
  - select:
      kind: Service
      name: ingress-nginx-controller
      namespace: ingress-nginx
    fieldPaths:
    - spec.ports.0.port
- source:
    kind: ConfigMap
    name: nginx-config
    fieldPath: data.HTTPS_PORT
  targets:
  - select:
      kind: Service
      name: ingress-nginx-controller
      namespace: ingress-nginx
    fieldPaths:
    - spec.ports.1.port


secretGenerator:
  - name: api-secrets
    type: Opaque
    namespace: 5stack
    envs:
      - secrets/api-secrets.env

  - name: timescaledb-secrets
    type: Opaque
    namespace: 5stack
    envs:
      - secrets/timescaledb-secrets.env
  - name: tailscale-secrets
    type: Opaque
    namespace: 5stack
    envs:
      - secrets/tailscale-secrets.env
  - name: steam-secrets
    type: Opaque
    namespace: 5stack
    envs:
      - secrets/steam-secrets.env
  - name: hasura-secrets
    type: Opaque
    namespace: 5stack
    envs:
      - secrets/hasura-secrets.env
  - name: discord-secrets
    type: Opaque
    namespace: 5stack
    envs:
      - secrets/discord-secrets.env
  - name: s3-secrets
    type: Opaque
    namespace: 5stack
    envs:
      - secrets/s3-secrets.env
  - name: redis-secrets
    type: Opaque
    namespace: 5stack
    envs:
      - secrets/redis-secrets.env
  - name: typesense-secrets
    type: Opaque
    namespace: 5stack
    envs:
      - secrets/typesense-secrets.env
  - name: minio-secrets
    type: Opaque
    namespace: 5stack
    envs:
      - secrets/minio-secrets.env
  - name: faceit-secrets
    type: Opaque
    namespace: 5stack
    envs:
      - secrets/faceit-secrets.env

#  TODO - disable dev mode for hasura in prod
# HASURA_GRAPHQL_DEV_MODE