apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - api
  - game-server-node-connector
  - hasura
  - minio
  - timescaledb
  - redis
  - typesense
  - web
  - volumes
  - nginx