apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: server-creator-clusterrole
rules:
  - apiGroups:
      - ''
    resources:
      - nodes
    verbs:
      - get
      - list
      - patch
  - apiGroups:
      - ''
    resources:
      - persistentvolumeclaims
    verbs:
      - create
      - get
      - list
      - watch
      - delete
  - apiGroups:
      - ''
    resources:
      - persistentvolumes
    verbs:
      - create
      - get
      - list
      - watch
      - delete
  - apiGroups:
      - batch
    resources:
      - jobs
      - jobs/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch